import { db } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";
import { AnalysisResult } from "@/types/analysis";
import { ReportCardWrapper } from "./ReportCardWrapper";
import { Navbar } from "@/components/Navbar";
import { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";

interface PageProps {
  params: Promise<{ id: string }>;
}

async function getReport(id: string): Promise<AnalysisResult | null> {
  const docRef = doc(db, "global_cache", id);
  const docSnap = await getDoc(docRef);

  if (!docSnap.exists()) {
    return null;
  }

  const data = docSnap.data();
  
  // Parse JSON strings back to objects if they are strings
  const parseSafe = (val: unknown) => {
    if (typeof val === "string") {
      try {
        return JSON.parse(val);
      } catch {
        return val;
      }
    }
    return val;
  };

  return {
    ...data,
    risks: parseSafe(data.risks) || [],
    goodPoints: parseSafe(data.goodPoints) || [],
    smokingGun: parseSafe(data.smokingGun),
    contentHash: id,
  } as AnalysisResult;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const report = await getReport(id);

  if (!report) {
    return {
      title: "Report Not Found | (To.S) Analyser",
    };
  }

  const title = `${report.appName || "Terms of Service"} Analysis - Grade ${report.grade}`;
  const description = report.summary || "Detailed analysis of Terms of Service risks and good points.";

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      images: [
        {
          url: `/api/og?id=${id}`, // We'll implement this OG image generator next
          width: 1200,
          height: 630,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`/api/og?id=${id}`],
    },
  };
}

export default async function ReportPage({ params }: PageProps) {
  const { id } = await params;
  const report = await getReport(id);

  if (!report) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-background selection:bg-primary/30 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[500px] bg-gradient-to-b from-primary/10 to-transparent blur-[120px] pointer-events-none" />
      
      <Navbar />
      
      <div className="max-w-4xl mx-auto px-4 pt-32 pb-20 relative z-10">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12 space-y-4 text-center"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-[10px] font-black uppercase tracking-[0.2em] text-primary">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
            </span>
            Verified Legal Audit
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight text-gradient">
            Audit Report
          </h1>
          <p className="text-foreground/60 font-medium max-w-lg mx-auto">
            A comprehensive breakdown of legal risks and transparency scores for this document.
          </p>
        </motion.div>
        
        <ReportCardWrapper result={report} />
        
        <footer className="mt-20 pt-12 border-t border-white/5 text-center space-y-8">
          <div className="space-y-4">
            <p className="text-xs text-foreground/40 max-w-md mx-auto leading-relaxed">
              This report was generated by (To.S) Analyser using our AI. 
              Our AI scans for known legal patterns but is not a substitute for professional legal advice.
            </p>
          </div>
          <div className="flex flex-col items-center gap-4">
            <Link 
              href="/" 
              className="group flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-white text-sm font-bold hover:bg-primary/90 transition-all shadow-xl shadow-primary/20"
            >
              Analyze Your Own Document
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
            <p className="text-[10px] font-black uppercase tracking-widest text-foreground/20">
              © 2026 (To.S) Analyser • Premium Design Eng
            </p>
          </div>
        </footer>
      </div>
    </main>
  );
}
