"use client";

import React from "react";
import { Download } from "lucide-react";
import { AnalysisResult, Risk, GoodPoint } from "@/types/analysis";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportButtonProps {
  data: AnalysisResult;
  appName?: string;
}

export default function ExportButton({ data, appName }: ExportButtonProps) {
  const exportPDF = () => {
    const doc = new jsPDF();
    const title = `${appName || data.appName || "Terms of Service"} Analysis Report`;
    const date = new Date().toLocaleDateString();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40);
    doc.text(title, 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by TOS Analyser on ${date}`, 14, 30);

    // Summary Section
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Executive Summary", 14, 45);
    
    doc.setFontSize(11);
    const splitSummary = doc.splitTextToSize(data.summary, 180);
    doc.text(splitSummary, 14, 52);

    let finalY = 52 + (splitSummary.length * 6);

    // Score and Grade
    doc.setFontSize(14);
    doc.text(`Grade: ${data.grade} | Score: ${data.transparencyScore}/100`, 14, finalY + 10);
    finalY += 25;

    // Risks Table
    if (data.risks && data.risks.length > 0) {
      doc.setFontSize(14);
      doc.text("Identified Risks", 14, finalY);
      
      const tableData = data.risks.map((risk: Risk) => [
        risk.title,
        risk.severity.toUpperCase(),
        risk.description
      ]);

      autoTable(doc, {
        startY: finalY + 5,
        head: [['Title', 'Severity', 'Description']],
        body: tableData,
        headStyles: { fillColor: [200, 0, 0] },
        theme: 'grid',
      });

      finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
    }

    // Good Points Table
    if (data.goodPoints && data.goodPoints.length > 0) {
      doc.setFontSize(14);
      doc.text("Good Points", 14, finalY);

      const goodData = data.goodPoints.map((point: GoodPoint) => [
        point.title,
        point.description
      ]);

      autoTable(doc, {
        startY: finalY + 5,
        head: [['Title', 'Description']],
        body: goodData,
        headStyles: { fillColor: [0, 150, 0] },
        theme: 'grid',
      });
    }

    doc.save(`${appName || "analysis"}-report.pdf`);
  };

  return (
    <button
      onClick={exportPDF}
      className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-all shadow-lg active:scale-95"
    >
      <Download size={18} />
      Export PDF
    </button>
  );
}
